// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: add.proto

package cn.ladd.grpcx.register.demo.add;

public final class AddOuterClass {
  private AddOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_ladd_grpcx_register_demo_add_RequestInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_ladd_grpcx_register_demo_add_RequestInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_ladd_grpcx_register_demo_add_ResponseInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_ladd_grpcx_register_demo_add_ResponseInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tadd.proto\022\037cn.ladd.grpcx.register.demo" +
      ".add\"#\n\013RequestInfo\022\t\n\001a\030\001 \001(\005\022\t\n\001b\030\002 \001(" +
      "\005\"\031\n\014ResponseInfo\022\t\n\001c\030\001 \001(\0052k\n\003Add\022d\n\003a" +
      "dd\022,.cn.ladd.grpcx.register.demo.add.Req" +
      "uestInfo\032-.cn.ladd.grpcx.register.demo.a" +
      "dd.ResponseInfo\"\000B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_ladd_grpcx_register_demo_add_RequestInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_ladd_grpcx_register_demo_add_RequestInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_ladd_grpcx_register_demo_add_RequestInfo_descriptor,
        new java.lang.String[] { "A", "B", });
    internal_static_cn_ladd_grpcx_register_demo_add_ResponseInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_ladd_grpcx_register_demo_add_ResponseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_ladd_grpcx_register_demo_add_ResponseInfo_descriptor,
        new java.lang.String[] { "C", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
