// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: monitor.proto

package cn.ladd.grpcx.monitor;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.ladd.grpcx.monitor.Empty)
    com.google.protobuf.MessageOrBuilder {
}
