// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: monitor.proto

package cn.ladd.grpcx.monitor;

public final class MonitorOuterClass {
  private MonitorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_ladd_grpcx_monitor_ServiceInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_ladd_grpcx_monitor_ServiceInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_ladd_grpcx_monitor_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_ladd_grpcx_monitor_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmonitor.proto\022\025cn.ladd.grpcx.monitor\"\326" +
      "\002\n\013ServiceInfo\022\024\n\014manufacturer\030\001 \001(\t\022\016\n\006" +
      "osName\030\002 \001(\t\022\021\n\tosVersion\030\003 \001(\t\022\024\n\014avail" +
      "ableRam\030\004 \001(\t\022\020\n\010totalRam\030\005 \001(\t\022\025\n\ravail" +
      "ableDisk\030\006 \001(\t\022\021\n\ttotalDisk\030\007 \001(\t\022\027\n\017ava" +
      "ilableJVMMem\030\010 \001(\t\022\023\n\013totalJVMMem\030\t \001(\t\022" +
      "\020\n\010hostName\030\n \001(\t\022\023\n\013ipv4Address\030\013 \001(\t\022\023" +
      "\n\013ipv6Address\030\014 \001(\t\022\017\n\007cpuLoad\030\r \001(\t\022\023\n\013" +
      "serviceName\030\016 \001(\t\022\021\n\tlocalPort\030\017 \001(\t\022\031\n\021" +
      "loadblanceStategy\030\020 \001(\t\"\007\n\005Empty2\\\n\007Moni",
      "tor\022Q\n\013sendSysInfo\022\".cn.ladd.grpcx.monit" +
      "or.ServiceInfo\032\034.cn.ladd.grpcx.monitor.E" +
      "mpty\"\000B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_ladd_grpcx_monitor_ServiceInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_ladd_grpcx_monitor_ServiceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_ladd_grpcx_monitor_ServiceInfo_descriptor,
        new java.lang.String[] { "Manufacturer", "OsName", "OsVersion", "AvailableRam", "TotalRam", "AvailableDisk", "TotalDisk", "AvailableJVMMem", "TotalJVMMem", "HostName", "Ipv4Address", "Ipv6Address", "CpuLoad", "ServiceName", "LocalPort", "LoadblanceStategy", });
    internal_static_cn_ladd_grpcx_monitor_Empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_ladd_grpcx_monitor_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_ladd_grpcx_monitor_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
