// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: monitor.proto

package cn.ladd.grpcx.monitor;

public interface ServiceInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.ladd.grpcx.monitor.ServiceInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string manufacturer = 1;</code>
   */
  java.lang.String getManufacturer();
  /**
   * <code>string manufacturer = 1;</code>
   */
  com.google.protobuf.ByteString
      getManufacturerBytes();

  /**
   * <code>string osName = 2;</code>
   */
  java.lang.String getOsName();
  /**
   * <code>string osName = 2;</code>
   */
  com.google.protobuf.ByteString
      getOsNameBytes();

  /**
   * <code>string osVersion = 3;</code>
   */
  java.lang.String getOsVersion();
  /**
   * <code>string osVersion = 3;</code>
   */
  com.google.protobuf.ByteString
      getOsVersionBytes();

  /**
   * <code>string availableRam = 4;</code>
   */
  java.lang.String getAvailableRam();
  /**
   * <code>string availableRam = 4;</code>
   */
  com.google.protobuf.ByteString
      getAvailableRamBytes();

  /**
   * <code>string totalRam = 5;</code>
   */
  java.lang.String getTotalRam();
  /**
   * <code>string totalRam = 5;</code>
   */
  com.google.protobuf.ByteString
      getTotalRamBytes();

  /**
   * <code>string availableDisk = 6;</code>
   */
  java.lang.String getAvailableDisk();
  /**
   * <code>string availableDisk = 6;</code>
   */
  com.google.protobuf.ByteString
      getAvailableDiskBytes();

  /**
   * <code>string totalDisk = 7;</code>
   */
  java.lang.String getTotalDisk();
  /**
   * <code>string totalDisk = 7;</code>
   */
  com.google.protobuf.ByteString
      getTotalDiskBytes();

  /**
   * <code>string availableJVMMem = 8;</code>
   */
  java.lang.String getAvailableJVMMem();
  /**
   * <code>string availableJVMMem = 8;</code>
   */
  com.google.protobuf.ByteString
      getAvailableJVMMemBytes();

  /**
   * <code>string totalJVMMem = 9;</code>
   */
  java.lang.String getTotalJVMMem();
  /**
   * <code>string totalJVMMem = 9;</code>
   */
  com.google.protobuf.ByteString
      getTotalJVMMemBytes();

  /**
   * <code>string hostName = 10;</code>
   */
  java.lang.String getHostName();
  /**
   * <code>string hostName = 10;</code>
   */
  com.google.protobuf.ByteString
      getHostNameBytes();

  /**
   * <code>string ipv4Address = 11;</code>
   */
  java.lang.String getIpv4Address();
  /**
   * <code>string ipv4Address = 11;</code>
   */
  com.google.protobuf.ByteString
      getIpv4AddressBytes();

  /**
   * <code>string ipv6Address = 12;</code>
   */
  java.lang.String getIpv6Address();
  /**
   * <code>string ipv6Address = 12;</code>
   */
  com.google.protobuf.ByteString
      getIpv6AddressBytes();

  /**
   * <code>string cpuLoad = 13;</code>
   */
  java.lang.String getCpuLoad();
  /**
   * <code>string cpuLoad = 13;</code>
   */
  com.google.protobuf.ByteString
      getCpuLoadBytes();

  /**
   * <code>string serviceName = 14;</code>
   */
  java.lang.String getServiceName();
  /**
   * <code>string serviceName = 14;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>string localPort = 15;</code>
   */
  java.lang.String getLocalPort();
  /**
   * <code>string localPort = 15;</code>
   */
  com.google.protobuf.ByteString
      getLocalPortBytes();

  /**
   * <code>string loadblanceStategy = 16;</code>
   */
  java.lang.String getLoadblanceStategy();
  /**
   * <code>string loadblanceStategy = 16;</code>
   */
  com.google.protobuf.ByteString
      getLoadblanceStategyBytes();
}
