// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartBeat.proto

package cn.ladd.grpcx.register.heartbeat.common;

public interface BeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.ladd.grpcx.register.heartbeat.common.BeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serviceName = 1;</code>
   */
  java.lang.String getServiceName();
  /**
   * <code>string serviceName = 1;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>.cn.ladd.grpcx.register.heartbeat.common.ServerInfo serverInfo = 2;</code>
   */
  boolean hasServerInfo();
  /**
   * <code>.cn.ladd.grpcx.register.heartbeat.common.ServerInfo serverInfo = 2;</code>
   */
  cn.ladd.grpcx.register.heartbeat.common.ServerInfo getServerInfo();
  /**
   * <code>.cn.ladd.grpcx.register.heartbeat.common.ServerInfo serverInfo = 2;</code>
   */
  cn.ladd.grpcx.register.heartbeat.common.ServerInfoOrBuilder getServerInfoOrBuilder();
}
