// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartBeat.proto

package cn.ladd.grpcx.register.heartbeat.common;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.ladd.grpcx.register.heartbeat.common.Empty)
    com.google.protobuf.MessageOrBuilder {
}
