// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartBeat.proto

package cn.ladd.grpcx.register.heartbeat.common;

public final class HeartBeatOuterClass {
  private HeartBeatOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_ladd_grpcx_register_heartbeat_common_ServerInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_ladd_grpcx_register_heartbeat_common_ServerInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_ladd_grpcx_register_heartbeat_common_BeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_ladd_grpcx_register_heartbeat_common_BeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_ladd_grpcx_register_heartbeat_common_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_ladd_grpcx_register_heartbeat_common_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017heartBeat.proto\022\'cn.ladd.grpcx.registe" +
      "r.heartbeat.common\"&\n\nServerInfo\022\n\n\002ip\030\001" +
      " \001(\t\022\014\n\004port\030\002 \001(\t\"k\n\013BeatRequest\022\023\n\013ser" +
      "viceName\030\001 \001(\t\022G\n\nserverInfo\030\002 \001(\01323.cn." +
      "ladd.grpcx.register.heartbeat.common.Ser" +
      "verInfo\"\007\n\005Empty2{\n\tHeartBeat\022n\n\004beat\0224." +
      "cn.ladd.grpcx.register.heartbeat.common." +
      "BeatRequest\032..cn.ladd.grpcx.register.hea" +
      "rtbeat.common.Empty\"\000B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_ladd_grpcx_register_heartbeat_common_ServerInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_ladd_grpcx_register_heartbeat_common_ServerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_ladd_grpcx_register_heartbeat_common_ServerInfo_descriptor,
        new java.lang.String[] { "Ip", "Port", });
    internal_static_cn_ladd_grpcx_register_heartbeat_common_BeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_ladd_grpcx_register_heartbeat_common_BeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_ladd_grpcx_register_heartbeat_common_BeatRequest_descriptor,
        new java.lang.String[] { "ServiceName", "ServerInfo", });
    internal_static_cn_ladd_grpcx_register_heartbeat_common_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cn_ladd_grpcx_register_heartbeat_common_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_ladd_grpcx_register_heartbeat_common_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
