// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartBeat.proto

package cn.ladd.grpcx.register.heartbeat.common;

public interface ServerInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.ladd.grpcx.register.heartbeat.common.ServerInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1;</code>
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>string port = 2;</code>
   */
  java.lang.String getPort();
  /**
   * <code>string port = 2;</code>
   */
  com.google.protobuf.ByteString
      getPortBytes();
}
