language: java
sudo: required

jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9


  
services:
  - docker

before_install:
  - docker pull zookeeper
  - docker run --name some-zookeeper -p 127.0.0.1:2181:2181 --restart always -d zookeeper
  - docker ps -a
