// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: add.proto

package cn.ladd.grpcx.register.demo.add;

public interface ResponseInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.ladd.grpcx.register.demo.add.ResponseInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 c = 1;</code>
   */
  int getC();
}
