// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: add.proto

package cn.ladd.grpcx.register.demo.add;

public interface RequestInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.ladd.grpcx.register.demo.add.RequestInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 a = 1;</code>
   */
  int getA();

  /**
   * <code>int32 b = 2;</code>
   */
  int getB();
}
