// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register.proto

package cn.ladd.grpcx.register.common;

/**
 * Protobuf type {@code cn.ladd.grpcx.register.common.BeatRequest}
 */
public  final class BeatRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.ladd.grpcx.register.common.BeatRequest)
    BeatRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BeatRequest.newBuilder() to construct.
  private BeatRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BeatRequest() {
    isConsumer_ = false;
    serviceNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BeatRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            isConsumer_ = input.readBool();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              serviceNames_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            serviceNames_.add(s);
            break;
          }
          case 26: {
            cn.ladd.grpcx.register.common.HostInfo.Builder subBuilder = null;
            if (hostInfo_ != null) {
              subBuilder = hostInfo_.toBuilder();
            }
            hostInfo_ = input.readMessage(cn.ladd.grpcx.register.common.HostInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(hostInfo_);
              hostInfo_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        serviceNames_ = serviceNames_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.ladd.grpcx.register.common.RegisterOuterClass.internal_static_cn_ladd_grpcx_register_common_BeatRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.ladd.grpcx.register.common.RegisterOuterClass.internal_static_cn_ladd_grpcx_register_common_BeatRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.ladd.grpcx.register.common.BeatRequest.class, cn.ladd.grpcx.register.common.BeatRequest.Builder.class);
  }

  private int bitField0_;
  public static final int ISCONSUMER_FIELD_NUMBER = 1;
  private boolean isConsumer_;
  /**
   * <code>bool isConsumer = 1;</code>
   */
  public boolean getIsConsumer() {
    return isConsumer_;
  }

  public static final int SERVICENAMES_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList serviceNames_;
  /**
   * <code>repeated string serviceNames = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getServiceNamesList() {
    return serviceNames_;
  }
  /**
   * <code>repeated string serviceNames = 2;</code>
   */
  public int getServiceNamesCount() {
    return serviceNames_.size();
  }
  /**
   * <code>repeated string serviceNames = 2;</code>
   */
  public java.lang.String getServiceNames(int index) {
    return serviceNames_.get(index);
  }
  /**
   * <code>repeated string serviceNames = 2;</code>
   */
  public com.google.protobuf.ByteString
      getServiceNamesBytes(int index) {
    return serviceNames_.getByteString(index);
  }

  public static final int HOSTINFO_FIELD_NUMBER = 3;
  private cn.ladd.grpcx.register.common.HostInfo hostInfo_;
  /**
   * <code>.cn.ladd.grpcx.register.common.HostInfo hostInfo = 3;</code>
   */
  public boolean hasHostInfo() {
    return hostInfo_ != null;
  }
  /**
   * <code>.cn.ladd.grpcx.register.common.HostInfo hostInfo = 3;</code>
   */
  public cn.ladd.grpcx.register.common.HostInfo getHostInfo() {
    return hostInfo_ == null ? cn.ladd.grpcx.register.common.HostInfo.getDefaultInstance() : hostInfo_;
  }
  /**
   * <code>.cn.ladd.grpcx.register.common.HostInfo hostInfo = 3;</code>
   */
  public cn.ladd.grpcx.register.common.HostInfoOrBuilder getHostInfoOrBuilder() {
    return getHostInfo();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isConsumer_ != false) {
      output.writeBool(1, isConsumer_);
    }
    for (int i = 0; i < serviceNames_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serviceNames_.getRaw(i));
    }
    if (hostInfo_ != null) {
      output.writeMessage(3, getHostInfo());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isConsumer_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isConsumer_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < serviceNames_.size(); i++) {
        dataSize += computeStringSizeNoTag(serviceNames_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getServiceNamesList().size();
    }
    if (hostInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getHostInfo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.ladd.grpcx.register.common.BeatRequest)) {
      return super.equals(obj);
    }
    cn.ladd.grpcx.register.common.BeatRequest other = (cn.ladd.grpcx.register.common.BeatRequest) obj;

    boolean result = true;
    result = result && (getIsConsumer()
        == other.getIsConsumer());
    result = result && getServiceNamesList()
        .equals(other.getServiceNamesList());
    result = result && (hasHostInfo() == other.hasHostInfo());
    if (hasHostInfo()) {
      result = result && getHostInfo()
          .equals(other.getHostInfo());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ISCONSUMER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsConsumer());
    if (getServiceNamesCount() > 0) {
      hash = (37 * hash) + SERVICENAMES_FIELD_NUMBER;
      hash = (53 * hash) + getServiceNamesList().hashCode();
    }
    if (hasHostInfo()) {
      hash = (37 * hash) + HOSTINFO_FIELD_NUMBER;
      hash = (53 * hash) + getHostInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.ladd.grpcx.register.common.BeatRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ladd.grpcx.register.common.BeatRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ladd.grpcx.register.common.BeatRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ladd.grpcx.register.common.BeatRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ladd.grpcx.register.common.BeatRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ladd.grpcx.register.common.BeatRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ladd.grpcx.register.common.BeatRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ladd.grpcx.register.common.BeatRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ladd.grpcx.register.common.BeatRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.ladd.grpcx.register.common.BeatRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ladd.grpcx.register.common.BeatRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ladd.grpcx.register.common.BeatRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.ladd.grpcx.register.common.BeatRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cn.ladd.grpcx.register.common.BeatRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.ladd.grpcx.register.common.BeatRequest)
      cn.ladd.grpcx.register.common.BeatRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ladd.grpcx.register.common.RegisterOuterClass.internal_static_cn_ladd_grpcx_register_common_BeatRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ladd.grpcx.register.common.RegisterOuterClass.internal_static_cn_ladd_grpcx_register_common_BeatRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ladd.grpcx.register.common.BeatRequest.class, cn.ladd.grpcx.register.common.BeatRequest.Builder.class);
    }

    // Construct using cn.ladd.grpcx.register.common.BeatRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      isConsumer_ = false;

      serviceNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      if (hostInfoBuilder_ == null) {
        hostInfo_ = null;
      } else {
        hostInfo_ = null;
        hostInfoBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.ladd.grpcx.register.common.RegisterOuterClass.internal_static_cn_ladd_grpcx_register_common_BeatRequest_descriptor;
    }

    public cn.ladd.grpcx.register.common.BeatRequest getDefaultInstanceForType() {
      return cn.ladd.grpcx.register.common.BeatRequest.getDefaultInstance();
    }

    public cn.ladd.grpcx.register.common.BeatRequest build() {
      cn.ladd.grpcx.register.common.BeatRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cn.ladd.grpcx.register.common.BeatRequest buildPartial() {
      cn.ladd.grpcx.register.common.BeatRequest result = new cn.ladd.grpcx.register.common.BeatRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.isConsumer_ = isConsumer_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        serviceNames_ = serviceNames_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.serviceNames_ = serviceNames_;
      if (hostInfoBuilder_ == null) {
        result.hostInfo_ = hostInfo_;
      } else {
        result.hostInfo_ = hostInfoBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.ladd.grpcx.register.common.BeatRequest) {
        return mergeFrom((cn.ladd.grpcx.register.common.BeatRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.ladd.grpcx.register.common.BeatRequest other) {
      if (other == cn.ladd.grpcx.register.common.BeatRequest.getDefaultInstance()) return this;
      if (other.getIsConsumer() != false) {
        setIsConsumer(other.getIsConsumer());
      }
      if (!other.serviceNames_.isEmpty()) {
        if (serviceNames_.isEmpty()) {
          serviceNames_ = other.serviceNames_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureServiceNamesIsMutable();
          serviceNames_.addAll(other.serviceNames_);
        }
        onChanged();
      }
      if (other.hasHostInfo()) {
        mergeHostInfo(other.getHostInfo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.ladd.grpcx.register.common.BeatRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.ladd.grpcx.register.common.BeatRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean isConsumer_ ;
    /**
     * <code>bool isConsumer = 1;</code>
     */
    public boolean getIsConsumer() {
      return isConsumer_;
    }
    /**
     * <code>bool isConsumer = 1;</code>
     */
    public Builder setIsConsumer(boolean value) {
      
      isConsumer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isConsumer = 1;</code>
     */
    public Builder clearIsConsumer() {
      
      isConsumer_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList serviceNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureServiceNamesIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        serviceNames_ = new com.google.protobuf.LazyStringArrayList(serviceNames_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string serviceNames = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getServiceNamesList() {
      return serviceNames_.getUnmodifiableView();
    }
    /**
     * <code>repeated string serviceNames = 2;</code>
     */
    public int getServiceNamesCount() {
      return serviceNames_.size();
    }
    /**
     * <code>repeated string serviceNames = 2;</code>
     */
    public java.lang.String getServiceNames(int index) {
      return serviceNames_.get(index);
    }
    /**
     * <code>repeated string serviceNames = 2;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNamesBytes(int index) {
      return serviceNames_.getByteString(index);
    }
    /**
     * <code>repeated string serviceNames = 2;</code>
     */
    public Builder setServiceNames(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureServiceNamesIsMutable();
      serviceNames_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string serviceNames = 2;</code>
     */
    public Builder addServiceNames(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureServiceNamesIsMutable();
      serviceNames_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string serviceNames = 2;</code>
     */
    public Builder addAllServiceNames(
        java.lang.Iterable<java.lang.String> values) {
      ensureServiceNamesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, serviceNames_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string serviceNames = 2;</code>
     */
    public Builder clearServiceNames() {
      serviceNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string serviceNames = 2;</code>
     */
    public Builder addServiceNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureServiceNamesIsMutable();
      serviceNames_.add(value);
      onChanged();
      return this;
    }

    private cn.ladd.grpcx.register.common.HostInfo hostInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.ladd.grpcx.register.common.HostInfo, cn.ladd.grpcx.register.common.HostInfo.Builder, cn.ladd.grpcx.register.common.HostInfoOrBuilder> hostInfoBuilder_;
    /**
     * <code>.cn.ladd.grpcx.register.common.HostInfo hostInfo = 3;</code>
     */
    public boolean hasHostInfo() {
      return hostInfoBuilder_ != null || hostInfo_ != null;
    }
    /**
     * <code>.cn.ladd.grpcx.register.common.HostInfo hostInfo = 3;</code>
     */
    public cn.ladd.grpcx.register.common.HostInfo getHostInfo() {
      if (hostInfoBuilder_ == null) {
        return hostInfo_ == null ? cn.ladd.grpcx.register.common.HostInfo.getDefaultInstance() : hostInfo_;
      } else {
        return hostInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.cn.ladd.grpcx.register.common.HostInfo hostInfo = 3;</code>
     */
    public Builder setHostInfo(cn.ladd.grpcx.register.common.HostInfo value) {
      if (hostInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        hostInfo_ = value;
        onChanged();
      } else {
        hostInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.cn.ladd.grpcx.register.common.HostInfo hostInfo = 3;</code>
     */
    public Builder setHostInfo(
        cn.ladd.grpcx.register.common.HostInfo.Builder builderForValue) {
      if (hostInfoBuilder_ == null) {
        hostInfo_ = builderForValue.build();
        onChanged();
      } else {
        hostInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.cn.ladd.grpcx.register.common.HostInfo hostInfo = 3;</code>
     */
    public Builder mergeHostInfo(cn.ladd.grpcx.register.common.HostInfo value) {
      if (hostInfoBuilder_ == null) {
        if (hostInfo_ != null) {
          hostInfo_ =
            cn.ladd.grpcx.register.common.HostInfo.newBuilder(hostInfo_).mergeFrom(value).buildPartial();
        } else {
          hostInfo_ = value;
        }
        onChanged();
      } else {
        hostInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.cn.ladd.grpcx.register.common.HostInfo hostInfo = 3;</code>
     */
    public Builder clearHostInfo() {
      if (hostInfoBuilder_ == null) {
        hostInfo_ = null;
        onChanged();
      } else {
        hostInfo_ = null;
        hostInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.cn.ladd.grpcx.register.common.HostInfo hostInfo = 3;</code>
     */
    public cn.ladd.grpcx.register.common.HostInfo.Builder getHostInfoBuilder() {
      
      onChanged();
      return getHostInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.cn.ladd.grpcx.register.common.HostInfo hostInfo = 3;</code>
     */
    public cn.ladd.grpcx.register.common.HostInfoOrBuilder getHostInfoOrBuilder() {
      if (hostInfoBuilder_ != null) {
        return hostInfoBuilder_.getMessageOrBuilder();
      } else {
        return hostInfo_ == null ?
            cn.ladd.grpcx.register.common.HostInfo.getDefaultInstance() : hostInfo_;
      }
    }
    /**
     * <code>.cn.ladd.grpcx.register.common.HostInfo hostInfo = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.ladd.grpcx.register.common.HostInfo, cn.ladd.grpcx.register.common.HostInfo.Builder, cn.ladd.grpcx.register.common.HostInfoOrBuilder> 
        getHostInfoFieldBuilder() {
      if (hostInfoBuilder_ == null) {
        hostInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            cn.ladd.grpcx.register.common.HostInfo, cn.ladd.grpcx.register.common.HostInfo.Builder, cn.ladd.grpcx.register.common.HostInfoOrBuilder>(
                getHostInfo(),
                getParentForChildren(),
                isClean());
        hostInfo_ = null;
      }
      return hostInfoBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cn.ladd.grpcx.register.common.BeatRequest)
  }

  // @@protoc_insertion_point(class_scope:cn.ladd.grpcx.register.common.BeatRequest)
  private static final cn.ladd.grpcx.register.common.BeatRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.ladd.grpcx.register.common.BeatRequest();
  }

  public static cn.ladd.grpcx.register.common.BeatRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BeatRequest>
      PARSER = new com.google.protobuf.AbstractParser<BeatRequest>() {
    public BeatRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new BeatRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BeatRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BeatRequest> getParserForType() {
    return PARSER;
  }

  public cn.ladd.grpcx.register.common.BeatRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

