// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register.proto

package cn.ladd.grpcx.register.common;

/**
 * Protobuf type {@code cn.ladd.grpcx.register.common.LookupResponse}
 */
public  final class LookupResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.ladd.grpcx.register.common.LookupResponse)
    LookupResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LookupResponse.newBuilder() to construct.
  private LookupResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LookupResponse() {
    hostInfos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LookupResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              hostInfos_ = new java.util.ArrayList<cn.ladd.grpcx.register.common.HostInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            hostInfos_.add(
                input.readMessage(cn.ladd.grpcx.register.common.HostInfo.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        hostInfos_ = java.util.Collections.unmodifiableList(hostInfos_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.ladd.grpcx.register.common.RegisterOuterClass.internal_static_cn_ladd_grpcx_register_common_LookupResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.ladd.grpcx.register.common.RegisterOuterClass.internal_static_cn_ladd_grpcx_register_common_LookupResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.ladd.grpcx.register.common.LookupResponse.class, cn.ladd.grpcx.register.common.LookupResponse.Builder.class);
  }

  public static final int HOSTINFOS_FIELD_NUMBER = 1;
  private java.util.List<cn.ladd.grpcx.register.common.HostInfo> hostInfos_;
  /**
   * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
   */
  public java.util.List<cn.ladd.grpcx.register.common.HostInfo> getHostInfosList() {
    return hostInfos_;
  }
  /**
   * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
   */
  public java.util.List<? extends cn.ladd.grpcx.register.common.HostInfoOrBuilder> 
      getHostInfosOrBuilderList() {
    return hostInfos_;
  }
  /**
   * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
   */
  public int getHostInfosCount() {
    return hostInfos_.size();
  }
  /**
   * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
   */
  public cn.ladd.grpcx.register.common.HostInfo getHostInfos(int index) {
    return hostInfos_.get(index);
  }
  /**
   * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
   */
  public cn.ladd.grpcx.register.common.HostInfoOrBuilder getHostInfosOrBuilder(
      int index) {
    return hostInfos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < hostInfos_.size(); i++) {
      output.writeMessage(1, hostInfos_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < hostInfos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, hostInfos_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.ladd.grpcx.register.common.LookupResponse)) {
      return super.equals(obj);
    }
    cn.ladd.grpcx.register.common.LookupResponse other = (cn.ladd.grpcx.register.common.LookupResponse) obj;

    boolean result = true;
    result = result && getHostInfosList()
        .equals(other.getHostInfosList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getHostInfosCount() > 0) {
      hash = (37 * hash) + HOSTINFOS_FIELD_NUMBER;
      hash = (53 * hash) + getHostInfosList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.ladd.grpcx.register.common.LookupResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ladd.grpcx.register.common.LookupResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ladd.grpcx.register.common.LookupResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ladd.grpcx.register.common.LookupResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ladd.grpcx.register.common.LookupResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ladd.grpcx.register.common.LookupResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ladd.grpcx.register.common.LookupResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ladd.grpcx.register.common.LookupResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ladd.grpcx.register.common.LookupResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.ladd.grpcx.register.common.LookupResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ladd.grpcx.register.common.LookupResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ladd.grpcx.register.common.LookupResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.ladd.grpcx.register.common.LookupResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cn.ladd.grpcx.register.common.LookupResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.ladd.grpcx.register.common.LookupResponse)
      cn.ladd.grpcx.register.common.LookupResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ladd.grpcx.register.common.RegisterOuterClass.internal_static_cn_ladd_grpcx_register_common_LookupResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ladd.grpcx.register.common.RegisterOuterClass.internal_static_cn_ladd_grpcx_register_common_LookupResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ladd.grpcx.register.common.LookupResponse.class, cn.ladd.grpcx.register.common.LookupResponse.Builder.class);
    }

    // Construct using cn.ladd.grpcx.register.common.LookupResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getHostInfosFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (hostInfosBuilder_ == null) {
        hostInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        hostInfosBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.ladd.grpcx.register.common.RegisterOuterClass.internal_static_cn_ladd_grpcx_register_common_LookupResponse_descriptor;
    }

    public cn.ladd.grpcx.register.common.LookupResponse getDefaultInstanceForType() {
      return cn.ladd.grpcx.register.common.LookupResponse.getDefaultInstance();
    }

    public cn.ladd.grpcx.register.common.LookupResponse build() {
      cn.ladd.grpcx.register.common.LookupResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cn.ladd.grpcx.register.common.LookupResponse buildPartial() {
      cn.ladd.grpcx.register.common.LookupResponse result = new cn.ladd.grpcx.register.common.LookupResponse(this);
      int from_bitField0_ = bitField0_;
      if (hostInfosBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          hostInfos_ = java.util.Collections.unmodifiableList(hostInfos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.hostInfos_ = hostInfos_;
      } else {
        result.hostInfos_ = hostInfosBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.ladd.grpcx.register.common.LookupResponse) {
        return mergeFrom((cn.ladd.grpcx.register.common.LookupResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.ladd.grpcx.register.common.LookupResponse other) {
      if (other == cn.ladd.grpcx.register.common.LookupResponse.getDefaultInstance()) return this;
      if (hostInfosBuilder_ == null) {
        if (!other.hostInfos_.isEmpty()) {
          if (hostInfos_.isEmpty()) {
            hostInfos_ = other.hostInfos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureHostInfosIsMutable();
            hostInfos_.addAll(other.hostInfos_);
          }
          onChanged();
        }
      } else {
        if (!other.hostInfos_.isEmpty()) {
          if (hostInfosBuilder_.isEmpty()) {
            hostInfosBuilder_.dispose();
            hostInfosBuilder_ = null;
            hostInfos_ = other.hostInfos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            hostInfosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHostInfosFieldBuilder() : null;
          } else {
            hostInfosBuilder_.addAllMessages(other.hostInfos_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.ladd.grpcx.register.common.LookupResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.ladd.grpcx.register.common.LookupResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<cn.ladd.grpcx.register.common.HostInfo> hostInfos_ =
      java.util.Collections.emptyList();
    private void ensureHostInfosIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        hostInfos_ = new java.util.ArrayList<cn.ladd.grpcx.register.common.HostInfo>(hostInfos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.ladd.grpcx.register.common.HostInfo, cn.ladd.grpcx.register.common.HostInfo.Builder, cn.ladd.grpcx.register.common.HostInfoOrBuilder> hostInfosBuilder_;

    /**
     * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
     */
    public java.util.List<cn.ladd.grpcx.register.common.HostInfo> getHostInfosList() {
      if (hostInfosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(hostInfos_);
      } else {
        return hostInfosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
     */
    public int getHostInfosCount() {
      if (hostInfosBuilder_ == null) {
        return hostInfos_.size();
      } else {
        return hostInfosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
     */
    public cn.ladd.grpcx.register.common.HostInfo getHostInfos(int index) {
      if (hostInfosBuilder_ == null) {
        return hostInfos_.get(index);
      } else {
        return hostInfosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
     */
    public Builder setHostInfos(
        int index, cn.ladd.grpcx.register.common.HostInfo value) {
      if (hostInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHostInfosIsMutable();
        hostInfos_.set(index, value);
        onChanged();
      } else {
        hostInfosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
     */
    public Builder setHostInfos(
        int index, cn.ladd.grpcx.register.common.HostInfo.Builder builderForValue) {
      if (hostInfosBuilder_ == null) {
        ensureHostInfosIsMutable();
        hostInfos_.set(index, builderForValue.build());
        onChanged();
      } else {
        hostInfosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
     */
    public Builder addHostInfos(cn.ladd.grpcx.register.common.HostInfo value) {
      if (hostInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHostInfosIsMutable();
        hostInfos_.add(value);
        onChanged();
      } else {
        hostInfosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
     */
    public Builder addHostInfos(
        int index, cn.ladd.grpcx.register.common.HostInfo value) {
      if (hostInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHostInfosIsMutable();
        hostInfos_.add(index, value);
        onChanged();
      } else {
        hostInfosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
     */
    public Builder addHostInfos(
        cn.ladd.grpcx.register.common.HostInfo.Builder builderForValue) {
      if (hostInfosBuilder_ == null) {
        ensureHostInfosIsMutable();
        hostInfos_.add(builderForValue.build());
        onChanged();
      } else {
        hostInfosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
     */
    public Builder addHostInfos(
        int index, cn.ladd.grpcx.register.common.HostInfo.Builder builderForValue) {
      if (hostInfosBuilder_ == null) {
        ensureHostInfosIsMutable();
        hostInfos_.add(index, builderForValue.build());
        onChanged();
      } else {
        hostInfosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
     */
    public Builder addAllHostInfos(
        java.lang.Iterable<? extends cn.ladd.grpcx.register.common.HostInfo> values) {
      if (hostInfosBuilder_ == null) {
        ensureHostInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, hostInfos_);
        onChanged();
      } else {
        hostInfosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
     */
    public Builder clearHostInfos() {
      if (hostInfosBuilder_ == null) {
        hostInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        hostInfosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
     */
    public Builder removeHostInfos(int index) {
      if (hostInfosBuilder_ == null) {
        ensureHostInfosIsMutable();
        hostInfos_.remove(index);
        onChanged();
      } else {
        hostInfosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
     */
    public cn.ladd.grpcx.register.common.HostInfo.Builder getHostInfosBuilder(
        int index) {
      return getHostInfosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
     */
    public cn.ladd.grpcx.register.common.HostInfoOrBuilder getHostInfosOrBuilder(
        int index) {
      if (hostInfosBuilder_ == null) {
        return hostInfos_.get(index);  } else {
        return hostInfosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
     */
    public java.util.List<? extends cn.ladd.grpcx.register.common.HostInfoOrBuilder> 
         getHostInfosOrBuilderList() {
      if (hostInfosBuilder_ != null) {
        return hostInfosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(hostInfos_);
      }
    }
    /**
     * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
     */
    public cn.ladd.grpcx.register.common.HostInfo.Builder addHostInfosBuilder() {
      return getHostInfosFieldBuilder().addBuilder(
          cn.ladd.grpcx.register.common.HostInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
     */
    public cn.ladd.grpcx.register.common.HostInfo.Builder addHostInfosBuilder(
        int index) {
      return getHostInfosFieldBuilder().addBuilder(
          index, cn.ladd.grpcx.register.common.HostInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 1;</code>
     */
    public java.util.List<cn.ladd.grpcx.register.common.HostInfo.Builder> 
         getHostInfosBuilderList() {
      return getHostInfosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.ladd.grpcx.register.common.HostInfo, cn.ladd.grpcx.register.common.HostInfo.Builder, cn.ladd.grpcx.register.common.HostInfoOrBuilder> 
        getHostInfosFieldBuilder() {
      if (hostInfosBuilder_ == null) {
        hostInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cn.ladd.grpcx.register.common.HostInfo, cn.ladd.grpcx.register.common.HostInfo.Builder, cn.ladd.grpcx.register.common.HostInfoOrBuilder>(
                hostInfos_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        hostInfos_ = null;
      }
      return hostInfosBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cn.ladd.grpcx.register.common.LookupResponse)
  }

  // @@protoc_insertion_point(class_scope:cn.ladd.grpcx.register.common.LookupResponse)
  private static final cn.ladd.grpcx.register.common.LookupResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.ladd.grpcx.register.common.LookupResponse();
  }

  public static cn.ladd.grpcx.register.common.LookupResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LookupResponse>
      PARSER = new com.google.protobuf.AbstractParser<LookupResponse>() {
    public LookupResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new LookupResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LookupResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LookupResponse> getParserForType() {
    return PARSER;
  }

  public cn.ladd.grpcx.register.common.LookupResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

