// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register.proto

package cn.ladd.grpcx.register.common;

public interface RefreshRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.ladd.grpcx.register.common.RefreshRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serviceName = 1;</code>
   */
  java.lang.String getServiceName();
  /**
   * <code>string serviceName = 1;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 2;</code>
   */
  java.util.List<cn.ladd.grpcx.register.common.HostInfo> 
      getHostInfosList();
  /**
   * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 2;</code>
   */
  cn.ladd.grpcx.register.common.HostInfo getHostInfos(int index);
  /**
   * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 2;</code>
   */
  int getHostInfosCount();
  /**
   * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 2;</code>
   */
  java.util.List<? extends cn.ladd.grpcx.register.common.HostInfoOrBuilder> 
      getHostInfosOrBuilderList();
  /**
   * <code>repeated .cn.ladd.grpcx.register.common.HostInfo hostInfos = 2;</code>
   */
  cn.ladd.grpcx.register.common.HostInfoOrBuilder getHostInfosOrBuilder(
      int index);
}
