// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register.proto

package cn.ladd.grpcx.register.common;

public interface BeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.ladd.grpcx.register.common.BeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isCunsumer = 1;</code>
   */
  boolean getIsCunsumer();

  /**
   * <code>repeated string serviceNames = 2;</code>
   */
  java.util.List<java.lang.String>
      getServiceNamesList();
  /**
   * <code>repeated string serviceNames = 2;</code>
   */
  int getServiceNamesCount();
  /**
   * <code>repeated string serviceNames = 2;</code>
   */
  java.lang.String getServiceNames(int index);
  /**
   * <code>repeated string serviceNames = 2;</code>
   */
  com.google.protobuf.ByteString
      getServiceNamesBytes(int index);

  /**
   * <code>.cn.ladd.grpcx.register.common.HostInfo hostInfo = 3;</code>
   */
  boolean hasHostInfo();
  /**
   * <code>.cn.ladd.grpcx.register.common.HostInfo hostInfo = 3;</code>
   */
  cn.ladd.grpcx.register.common.HostInfo getHostInfo();
  /**
   * <code>.cn.ladd.grpcx.register.common.HostInfo hostInfo = 3;</code>
   */
  cn.ladd.grpcx.register.common.HostInfoOrBuilder getHostInfoOrBuilder();
}
