// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register.proto

package cn.ladd.grpcx.register.common;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.ladd.grpcx.register.common.Empty)
    com.google.protobuf.MessageOrBuilder {
}
