// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register.proto

package cn.ladd.grpcx.register.common;

/**
 * Protobuf type {@code cn.ladd.grpcx.register.common.GetAllServiceNamesResponse}
 */
public  final class GetAllServiceNamesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.ladd.grpcx.register.common.GetAllServiceNamesResponse)
    GetAllServiceNamesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAllServiceNamesResponse.newBuilder() to construct.
  private GetAllServiceNamesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAllServiceNamesResponse() {
    serviceNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetAllServiceNamesResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              serviceNames_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            serviceNames_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        serviceNames_ = serviceNames_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.ladd.grpcx.register.common.RegisterOuterClass.internal_static_cn_ladd_grpcx_register_common_GetAllServiceNamesResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.ladd.grpcx.register.common.RegisterOuterClass.internal_static_cn_ladd_grpcx_register_common_GetAllServiceNamesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.ladd.grpcx.register.common.GetAllServiceNamesResponse.class, cn.ladd.grpcx.register.common.GetAllServiceNamesResponse.Builder.class);
  }

  public static final int SERVICENAMES_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList serviceNames_;
  /**
   * <code>repeated string serviceNames = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getServiceNamesList() {
    return serviceNames_;
  }
  /**
   * <code>repeated string serviceNames = 1;</code>
   */
  public int getServiceNamesCount() {
    return serviceNames_.size();
  }
  /**
   * <code>repeated string serviceNames = 1;</code>
   */
  public java.lang.String getServiceNames(int index) {
    return serviceNames_.get(index);
  }
  /**
   * <code>repeated string serviceNames = 1;</code>
   */
  public com.google.protobuf.ByteString
      getServiceNamesBytes(int index) {
    return serviceNames_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < serviceNames_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serviceNames_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < serviceNames_.size(); i++) {
        dataSize += computeStringSizeNoTag(serviceNames_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getServiceNamesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.ladd.grpcx.register.common.GetAllServiceNamesResponse)) {
      return super.equals(obj);
    }
    cn.ladd.grpcx.register.common.GetAllServiceNamesResponse other = (cn.ladd.grpcx.register.common.GetAllServiceNamesResponse) obj;

    boolean result = true;
    result = result && getServiceNamesList()
        .equals(other.getServiceNamesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getServiceNamesCount() > 0) {
      hash = (37 * hash) + SERVICENAMES_FIELD_NUMBER;
      hash = (53 * hash) + getServiceNamesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.ladd.grpcx.register.common.GetAllServiceNamesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ladd.grpcx.register.common.GetAllServiceNamesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ladd.grpcx.register.common.GetAllServiceNamesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ladd.grpcx.register.common.GetAllServiceNamesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ladd.grpcx.register.common.GetAllServiceNamesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ladd.grpcx.register.common.GetAllServiceNamesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ladd.grpcx.register.common.GetAllServiceNamesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ladd.grpcx.register.common.GetAllServiceNamesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ladd.grpcx.register.common.GetAllServiceNamesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.ladd.grpcx.register.common.GetAllServiceNamesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ladd.grpcx.register.common.GetAllServiceNamesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ladd.grpcx.register.common.GetAllServiceNamesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.ladd.grpcx.register.common.GetAllServiceNamesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cn.ladd.grpcx.register.common.GetAllServiceNamesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.ladd.grpcx.register.common.GetAllServiceNamesResponse)
      cn.ladd.grpcx.register.common.GetAllServiceNamesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ladd.grpcx.register.common.RegisterOuterClass.internal_static_cn_ladd_grpcx_register_common_GetAllServiceNamesResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ladd.grpcx.register.common.RegisterOuterClass.internal_static_cn_ladd_grpcx_register_common_GetAllServiceNamesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ladd.grpcx.register.common.GetAllServiceNamesResponse.class, cn.ladd.grpcx.register.common.GetAllServiceNamesResponse.Builder.class);
    }

    // Construct using cn.ladd.grpcx.register.common.GetAllServiceNamesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      serviceNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.ladd.grpcx.register.common.RegisterOuterClass.internal_static_cn_ladd_grpcx_register_common_GetAllServiceNamesResponse_descriptor;
    }

    public cn.ladd.grpcx.register.common.GetAllServiceNamesResponse getDefaultInstanceForType() {
      return cn.ladd.grpcx.register.common.GetAllServiceNamesResponse.getDefaultInstance();
    }

    public cn.ladd.grpcx.register.common.GetAllServiceNamesResponse build() {
      cn.ladd.grpcx.register.common.GetAllServiceNamesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cn.ladd.grpcx.register.common.GetAllServiceNamesResponse buildPartial() {
      cn.ladd.grpcx.register.common.GetAllServiceNamesResponse result = new cn.ladd.grpcx.register.common.GetAllServiceNamesResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        serviceNames_ = serviceNames_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.serviceNames_ = serviceNames_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.ladd.grpcx.register.common.GetAllServiceNamesResponse) {
        return mergeFrom((cn.ladd.grpcx.register.common.GetAllServiceNamesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.ladd.grpcx.register.common.GetAllServiceNamesResponse other) {
      if (other == cn.ladd.grpcx.register.common.GetAllServiceNamesResponse.getDefaultInstance()) return this;
      if (!other.serviceNames_.isEmpty()) {
        if (serviceNames_.isEmpty()) {
          serviceNames_ = other.serviceNames_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureServiceNamesIsMutable();
          serviceNames_.addAll(other.serviceNames_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.ladd.grpcx.register.common.GetAllServiceNamesResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.ladd.grpcx.register.common.GetAllServiceNamesResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList serviceNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureServiceNamesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        serviceNames_ = new com.google.protobuf.LazyStringArrayList(serviceNames_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string serviceNames = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getServiceNamesList() {
      return serviceNames_.getUnmodifiableView();
    }
    /**
     * <code>repeated string serviceNames = 1;</code>
     */
    public int getServiceNamesCount() {
      return serviceNames_.size();
    }
    /**
     * <code>repeated string serviceNames = 1;</code>
     */
    public java.lang.String getServiceNames(int index) {
      return serviceNames_.get(index);
    }
    /**
     * <code>repeated string serviceNames = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNamesBytes(int index) {
      return serviceNames_.getByteString(index);
    }
    /**
     * <code>repeated string serviceNames = 1;</code>
     */
    public Builder setServiceNames(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureServiceNamesIsMutable();
      serviceNames_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string serviceNames = 1;</code>
     */
    public Builder addServiceNames(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureServiceNamesIsMutable();
      serviceNames_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string serviceNames = 1;</code>
     */
    public Builder addAllServiceNames(
        java.lang.Iterable<java.lang.String> values) {
      ensureServiceNamesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, serviceNames_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string serviceNames = 1;</code>
     */
    public Builder clearServiceNames() {
      serviceNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string serviceNames = 1;</code>
     */
    public Builder addServiceNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureServiceNamesIsMutable();
      serviceNames_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cn.ladd.grpcx.register.common.GetAllServiceNamesResponse)
  }

  // @@protoc_insertion_point(class_scope:cn.ladd.grpcx.register.common.GetAllServiceNamesResponse)
  private static final cn.ladd.grpcx.register.common.GetAllServiceNamesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.ladd.grpcx.register.common.GetAllServiceNamesResponse();
  }

  public static cn.ladd.grpcx.register.common.GetAllServiceNamesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAllServiceNamesResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAllServiceNamesResponse>() {
    public GetAllServiceNamesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetAllServiceNamesResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetAllServiceNamesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAllServiceNamesResponse> getParserForType() {
    return PARSER;
  }

  public cn.ladd.grpcx.register.common.GetAllServiceNamesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

