// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register.proto

package cn.ladd.grpcx.register.common;

public interface GetDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.ladd.grpcx.register.common.GetDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isCunsumer = 1;</code>
   */
  boolean getIsCunsumer();

  /**
   * <code>string serviceName = 2;</code>
   */
  java.lang.String getServiceName();
  /**
   * <code>string serviceName = 2;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>.cn.ladd.grpcx.register.common.HostInfo hostInfo = 3;</code>
   */
  boolean hasHostInfo();
  /**
   * <code>.cn.ladd.grpcx.register.common.HostInfo hostInfo = 3;</code>
   */
  cn.ladd.grpcx.register.common.HostInfo getHostInfo();
  /**
   * <code>.cn.ladd.grpcx.register.common.HostInfo hostInfo = 3;</code>
   */
  cn.ladd.grpcx.register.common.HostInfoOrBuilder getHostInfoOrBuilder();
}
