// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: monitor.proto

package cn.ladd.grpcx.monitor;

/**
 * Protobuf type {@code cn.ladd.grpcx.monitor.ServiceInfo}
 */
public  final class ServiceInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.ladd.grpcx.monitor.ServiceInfo)
    ServiceInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServiceInfo.newBuilder() to construct.
  private ServiceInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServiceInfo() {
    manufacturer_ = "";
    osName_ = "";
    osVersion_ = "";
    availableRam_ = "";
    totalRam_ = "";
    availableDisk_ = "";
    totalDisk_ = "";
    availableJVMMem_ = "";
    totalJVMMem_ = "";
    hostName_ = "";
    ipv4Address_ = "";
    ipv6Address_ = "";
    cpuLoad_ = "";
    serviceName_ = "";
    localPort_ = "";
    loadblanceStategy_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ServiceInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            manufacturer_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            osName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            osVersion_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            availableRam_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            totalRam_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            availableDisk_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            totalDisk_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            availableJVMMem_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            totalJVMMem_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            hostName_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            ipv4Address_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            ipv6Address_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            cpuLoad_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            serviceName_ = s;
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            localPort_ = s;
            break;
          }
          case 130: {
            java.lang.String s = input.readStringRequireUtf8();

            loadblanceStategy_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.ladd.grpcx.monitor.MonitorOuterClass.internal_static_cn_ladd_grpcx_monitor_ServiceInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.ladd.grpcx.monitor.MonitorOuterClass.internal_static_cn_ladd_grpcx_monitor_ServiceInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.ladd.grpcx.monitor.ServiceInfo.class, cn.ladd.grpcx.monitor.ServiceInfo.Builder.class);
  }

  public static final int MANUFACTURER_FIELD_NUMBER = 1;
  private volatile java.lang.Object manufacturer_;
  /**
   * <code>string manufacturer = 1;</code>
   */
  public java.lang.String getManufacturer() {
    java.lang.Object ref = manufacturer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      manufacturer_ = s;
      return s;
    }
  }
  /**
   * <code>string manufacturer = 1;</code>
   */
  public com.google.protobuf.ByteString
      getManufacturerBytes() {
    java.lang.Object ref = manufacturer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      manufacturer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OSNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object osName_;
  /**
   * <code>string osName = 2;</code>
   */
  public java.lang.String getOsName() {
    java.lang.Object ref = osName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      osName_ = s;
      return s;
    }
  }
  /**
   * <code>string osName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getOsNameBytes() {
    java.lang.Object ref = osName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      osName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OSVERSION_FIELD_NUMBER = 3;
  private volatile java.lang.Object osVersion_;
  /**
   * <code>string osVersion = 3;</code>
   */
  public java.lang.String getOsVersion() {
    java.lang.Object ref = osVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      osVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string osVersion = 3;</code>
   */
  public com.google.protobuf.ByteString
      getOsVersionBytes() {
    java.lang.Object ref = osVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      osVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVAILABLERAM_FIELD_NUMBER = 4;
  private volatile java.lang.Object availableRam_;
  /**
   * <code>string availableRam = 4;</code>
   */
  public java.lang.String getAvailableRam() {
    java.lang.Object ref = availableRam_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      availableRam_ = s;
      return s;
    }
  }
  /**
   * <code>string availableRam = 4;</code>
   */
  public com.google.protobuf.ByteString
      getAvailableRamBytes() {
    java.lang.Object ref = availableRam_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      availableRam_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTALRAM_FIELD_NUMBER = 5;
  private volatile java.lang.Object totalRam_;
  /**
   * <code>string totalRam = 5;</code>
   */
  public java.lang.String getTotalRam() {
    java.lang.Object ref = totalRam_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      totalRam_ = s;
      return s;
    }
  }
  /**
   * <code>string totalRam = 5;</code>
   */
  public com.google.protobuf.ByteString
      getTotalRamBytes() {
    java.lang.Object ref = totalRam_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      totalRam_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVAILABLEDISK_FIELD_NUMBER = 6;
  private volatile java.lang.Object availableDisk_;
  /**
   * <code>string availableDisk = 6;</code>
   */
  public java.lang.String getAvailableDisk() {
    java.lang.Object ref = availableDisk_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      availableDisk_ = s;
      return s;
    }
  }
  /**
   * <code>string availableDisk = 6;</code>
   */
  public com.google.protobuf.ByteString
      getAvailableDiskBytes() {
    java.lang.Object ref = availableDisk_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      availableDisk_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTALDISK_FIELD_NUMBER = 7;
  private volatile java.lang.Object totalDisk_;
  /**
   * <code>string totalDisk = 7;</code>
   */
  public java.lang.String getTotalDisk() {
    java.lang.Object ref = totalDisk_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      totalDisk_ = s;
      return s;
    }
  }
  /**
   * <code>string totalDisk = 7;</code>
   */
  public com.google.protobuf.ByteString
      getTotalDiskBytes() {
    java.lang.Object ref = totalDisk_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      totalDisk_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVAILABLEJVMMEM_FIELD_NUMBER = 8;
  private volatile java.lang.Object availableJVMMem_;
  /**
   * <code>string availableJVMMem = 8;</code>
   */
  public java.lang.String getAvailableJVMMem() {
    java.lang.Object ref = availableJVMMem_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      availableJVMMem_ = s;
      return s;
    }
  }
  /**
   * <code>string availableJVMMem = 8;</code>
   */
  public com.google.protobuf.ByteString
      getAvailableJVMMemBytes() {
    java.lang.Object ref = availableJVMMem_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      availableJVMMem_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTALJVMMEM_FIELD_NUMBER = 9;
  private volatile java.lang.Object totalJVMMem_;
  /**
   * <code>string totalJVMMem = 9;</code>
   */
  public java.lang.String getTotalJVMMem() {
    java.lang.Object ref = totalJVMMem_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      totalJVMMem_ = s;
      return s;
    }
  }
  /**
   * <code>string totalJVMMem = 9;</code>
   */
  public com.google.protobuf.ByteString
      getTotalJVMMemBytes() {
    java.lang.Object ref = totalJVMMem_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      totalJVMMem_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HOSTNAME_FIELD_NUMBER = 10;
  private volatile java.lang.Object hostName_;
  /**
   * <code>string hostName = 10;</code>
   */
  public java.lang.String getHostName() {
    java.lang.Object ref = hostName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hostName_ = s;
      return s;
    }
  }
  /**
   * <code>string hostName = 10;</code>
   */
  public com.google.protobuf.ByteString
      getHostNameBytes() {
    java.lang.Object ref = hostName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hostName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IPV4ADDRESS_FIELD_NUMBER = 11;
  private volatile java.lang.Object ipv4Address_;
  /**
   * <code>string ipv4Address = 11;</code>
   */
  public java.lang.String getIpv4Address() {
    java.lang.Object ref = ipv4Address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ipv4Address_ = s;
      return s;
    }
  }
  /**
   * <code>string ipv4Address = 11;</code>
   */
  public com.google.protobuf.ByteString
      getIpv4AddressBytes() {
    java.lang.Object ref = ipv4Address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ipv4Address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IPV6ADDRESS_FIELD_NUMBER = 12;
  private volatile java.lang.Object ipv6Address_;
  /**
   * <code>string ipv6Address = 12;</code>
   */
  public java.lang.String getIpv6Address() {
    java.lang.Object ref = ipv6Address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ipv6Address_ = s;
      return s;
    }
  }
  /**
   * <code>string ipv6Address = 12;</code>
   */
  public com.google.protobuf.ByteString
      getIpv6AddressBytes() {
    java.lang.Object ref = ipv6Address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ipv6Address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CPULOAD_FIELD_NUMBER = 13;
  private volatile java.lang.Object cpuLoad_;
  /**
   * <code>string cpuLoad = 13;</code>
   */
  public java.lang.String getCpuLoad() {
    java.lang.Object ref = cpuLoad_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cpuLoad_ = s;
      return s;
    }
  }
  /**
   * <code>string cpuLoad = 13;</code>
   */
  public com.google.protobuf.ByteString
      getCpuLoadBytes() {
    java.lang.Object ref = cpuLoad_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cpuLoad_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVICENAME_FIELD_NUMBER = 14;
  private volatile java.lang.Object serviceName_;
  /**
   * <code>string serviceName = 14;</code>
   */
  public java.lang.String getServiceName() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceName_ = s;
      return s;
    }
  }
  /**
   * <code>string serviceName = 14;</code>
   */
  public com.google.protobuf.ByteString
      getServiceNameBytes() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCALPORT_FIELD_NUMBER = 15;
  private volatile java.lang.Object localPort_;
  /**
   * <code>string localPort = 15;</code>
   */
  public java.lang.String getLocalPort() {
    java.lang.Object ref = localPort_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      localPort_ = s;
      return s;
    }
  }
  /**
   * <code>string localPort = 15;</code>
   */
  public com.google.protobuf.ByteString
      getLocalPortBytes() {
    java.lang.Object ref = localPort_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      localPort_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOADBLANCESTATEGY_FIELD_NUMBER = 16;
  private volatile java.lang.Object loadblanceStategy_;
  /**
   * <code>string loadblanceStategy = 16;</code>
   */
  public java.lang.String getLoadblanceStategy() {
    java.lang.Object ref = loadblanceStategy_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      loadblanceStategy_ = s;
      return s;
    }
  }
  /**
   * <code>string loadblanceStategy = 16;</code>
   */
  public com.google.protobuf.ByteString
      getLoadblanceStategyBytes() {
    java.lang.Object ref = loadblanceStategy_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      loadblanceStategy_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getManufacturerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, manufacturer_);
    }
    if (!getOsNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, osName_);
    }
    if (!getOsVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, osVersion_);
    }
    if (!getAvailableRamBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, availableRam_);
    }
    if (!getTotalRamBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, totalRam_);
    }
    if (!getAvailableDiskBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, availableDisk_);
    }
    if (!getTotalDiskBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, totalDisk_);
    }
    if (!getAvailableJVMMemBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, availableJVMMem_);
    }
    if (!getTotalJVMMemBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, totalJVMMem_);
    }
    if (!getHostNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, hostName_);
    }
    if (!getIpv4AddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, ipv4Address_);
    }
    if (!getIpv6AddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, ipv6Address_);
    }
    if (!getCpuLoadBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, cpuLoad_);
    }
    if (!getServiceNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, serviceName_);
    }
    if (!getLocalPortBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, localPort_);
    }
    if (!getLoadblanceStategyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, loadblanceStategy_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getManufacturerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, manufacturer_);
    }
    if (!getOsNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, osName_);
    }
    if (!getOsVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, osVersion_);
    }
    if (!getAvailableRamBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, availableRam_);
    }
    if (!getTotalRamBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, totalRam_);
    }
    if (!getAvailableDiskBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, availableDisk_);
    }
    if (!getTotalDiskBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, totalDisk_);
    }
    if (!getAvailableJVMMemBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, availableJVMMem_);
    }
    if (!getTotalJVMMemBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, totalJVMMem_);
    }
    if (!getHostNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, hostName_);
    }
    if (!getIpv4AddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, ipv4Address_);
    }
    if (!getIpv6AddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, ipv6Address_);
    }
    if (!getCpuLoadBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, cpuLoad_);
    }
    if (!getServiceNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, serviceName_);
    }
    if (!getLocalPortBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, localPort_);
    }
    if (!getLoadblanceStategyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, loadblanceStategy_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.ladd.grpcx.monitor.ServiceInfo)) {
      return super.equals(obj);
    }
    cn.ladd.grpcx.monitor.ServiceInfo other = (cn.ladd.grpcx.monitor.ServiceInfo) obj;

    boolean result = true;
    result = result && getManufacturer()
        .equals(other.getManufacturer());
    result = result && getOsName()
        .equals(other.getOsName());
    result = result && getOsVersion()
        .equals(other.getOsVersion());
    result = result && getAvailableRam()
        .equals(other.getAvailableRam());
    result = result && getTotalRam()
        .equals(other.getTotalRam());
    result = result && getAvailableDisk()
        .equals(other.getAvailableDisk());
    result = result && getTotalDisk()
        .equals(other.getTotalDisk());
    result = result && getAvailableJVMMem()
        .equals(other.getAvailableJVMMem());
    result = result && getTotalJVMMem()
        .equals(other.getTotalJVMMem());
    result = result && getHostName()
        .equals(other.getHostName());
    result = result && getIpv4Address()
        .equals(other.getIpv4Address());
    result = result && getIpv6Address()
        .equals(other.getIpv6Address());
    result = result && getCpuLoad()
        .equals(other.getCpuLoad());
    result = result && getServiceName()
        .equals(other.getServiceName());
    result = result && getLocalPort()
        .equals(other.getLocalPort());
    result = result && getLoadblanceStategy()
        .equals(other.getLoadblanceStategy());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MANUFACTURER_FIELD_NUMBER;
    hash = (53 * hash) + getManufacturer().hashCode();
    hash = (37 * hash) + OSNAME_FIELD_NUMBER;
    hash = (53 * hash) + getOsName().hashCode();
    hash = (37 * hash) + OSVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getOsVersion().hashCode();
    hash = (37 * hash) + AVAILABLERAM_FIELD_NUMBER;
    hash = (53 * hash) + getAvailableRam().hashCode();
    hash = (37 * hash) + TOTALRAM_FIELD_NUMBER;
    hash = (53 * hash) + getTotalRam().hashCode();
    hash = (37 * hash) + AVAILABLEDISK_FIELD_NUMBER;
    hash = (53 * hash) + getAvailableDisk().hashCode();
    hash = (37 * hash) + TOTALDISK_FIELD_NUMBER;
    hash = (53 * hash) + getTotalDisk().hashCode();
    hash = (37 * hash) + AVAILABLEJVMMEM_FIELD_NUMBER;
    hash = (53 * hash) + getAvailableJVMMem().hashCode();
    hash = (37 * hash) + TOTALJVMMEM_FIELD_NUMBER;
    hash = (53 * hash) + getTotalJVMMem().hashCode();
    hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getHostName().hashCode();
    hash = (37 * hash) + IPV4ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getIpv4Address().hashCode();
    hash = (37 * hash) + IPV6ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getIpv6Address().hashCode();
    hash = (37 * hash) + CPULOAD_FIELD_NUMBER;
    hash = (53 * hash) + getCpuLoad().hashCode();
    hash = (37 * hash) + SERVICENAME_FIELD_NUMBER;
    hash = (53 * hash) + getServiceName().hashCode();
    hash = (37 * hash) + LOCALPORT_FIELD_NUMBER;
    hash = (53 * hash) + getLocalPort().hashCode();
    hash = (37 * hash) + LOADBLANCESTATEGY_FIELD_NUMBER;
    hash = (53 * hash) + getLoadblanceStategy().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.ladd.grpcx.monitor.ServiceInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ladd.grpcx.monitor.ServiceInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ladd.grpcx.monitor.ServiceInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ladd.grpcx.monitor.ServiceInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ladd.grpcx.monitor.ServiceInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ladd.grpcx.monitor.ServiceInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ladd.grpcx.monitor.ServiceInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ladd.grpcx.monitor.ServiceInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ladd.grpcx.monitor.ServiceInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.ladd.grpcx.monitor.ServiceInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ladd.grpcx.monitor.ServiceInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ladd.grpcx.monitor.ServiceInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.ladd.grpcx.monitor.ServiceInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cn.ladd.grpcx.monitor.ServiceInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.ladd.grpcx.monitor.ServiceInfo)
      cn.ladd.grpcx.monitor.ServiceInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ladd.grpcx.monitor.MonitorOuterClass.internal_static_cn_ladd_grpcx_monitor_ServiceInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ladd.grpcx.monitor.MonitorOuterClass.internal_static_cn_ladd_grpcx_monitor_ServiceInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ladd.grpcx.monitor.ServiceInfo.class, cn.ladd.grpcx.monitor.ServiceInfo.Builder.class);
    }

    // Construct using cn.ladd.grpcx.monitor.ServiceInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      manufacturer_ = "";

      osName_ = "";

      osVersion_ = "";

      availableRam_ = "";

      totalRam_ = "";

      availableDisk_ = "";

      totalDisk_ = "";

      availableJVMMem_ = "";

      totalJVMMem_ = "";

      hostName_ = "";

      ipv4Address_ = "";

      ipv6Address_ = "";

      cpuLoad_ = "";

      serviceName_ = "";

      localPort_ = "";

      loadblanceStategy_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.ladd.grpcx.monitor.MonitorOuterClass.internal_static_cn_ladd_grpcx_monitor_ServiceInfo_descriptor;
    }

    public cn.ladd.grpcx.monitor.ServiceInfo getDefaultInstanceForType() {
      return cn.ladd.grpcx.monitor.ServiceInfo.getDefaultInstance();
    }

    public cn.ladd.grpcx.monitor.ServiceInfo build() {
      cn.ladd.grpcx.monitor.ServiceInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cn.ladd.grpcx.monitor.ServiceInfo buildPartial() {
      cn.ladd.grpcx.monitor.ServiceInfo result = new cn.ladd.grpcx.monitor.ServiceInfo(this);
      result.manufacturer_ = manufacturer_;
      result.osName_ = osName_;
      result.osVersion_ = osVersion_;
      result.availableRam_ = availableRam_;
      result.totalRam_ = totalRam_;
      result.availableDisk_ = availableDisk_;
      result.totalDisk_ = totalDisk_;
      result.availableJVMMem_ = availableJVMMem_;
      result.totalJVMMem_ = totalJVMMem_;
      result.hostName_ = hostName_;
      result.ipv4Address_ = ipv4Address_;
      result.ipv6Address_ = ipv6Address_;
      result.cpuLoad_ = cpuLoad_;
      result.serviceName_ = serviceName_;
      result.localPort_ = localPort_;
      result.loadblanceStategy_ = loadblanceStategy_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.ladd.grpcx.monitor.ServiceInfo) {
        return mergeFrom((cn.ladd.grpcx.monitor.ServiceInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.ladd.grpcx.monitor.ServiceInfo other) {
      if (other == cn.ladd.grpcx.monitor.ServiceInfo.getDefaultInstance()) return this;
      if (!other.getManufacturer().isEmpty()) {
        manufacturer_ = other.manufacturer_;
        onChanged();
      }
      if (!other.getOsName().isEmpty()) {
        osName_ = other.osName_;
        onChanged();
      }
      if (!other.getOsVersion().isEmpty()) {
        osVersion_ = other.osVersion_;
        onChanged();
      }
      if (!other.getAvailableRam().isEmpty()) {
        availableRam_ = other.availableRam_;
        onChanged();
      }
      if (!other.getTotalRam().isEmpty()) {
        totalRam_ = other.totalRam_;
        onChanged();
      }
      if (!other.getAvailableDisk().isEmpty()) {
        availableDisk_ = other.availableDisk_;
        onChanged();
      }
      if (!other.getTotalDisk().isEmpty()) {
        totalDisk_ = other.totalDisk_;
        onChanged();
      }
      if (!other.getAvailableJVMMem().isEmpty()) {
        availableJVMMem_ = other.availableJVMMem_;
        onChanged();
      }
      if (!other.getTotalJVMMem().isEmpty()) {
        totalJVMMem_ = other.totalJVMMem_;
        onChanged();
      }
      if (!other.getHostName().isEmpty()) {
        hostName_ = other.hostName_;
        onChanged();
      }
      if (!other.getIpv4Address().isEmpty()) {
        ipv4Address_ = other.ipv4Address_;
        onChanged();
      }
      if (!other.getIpv6Address().isEmpty()) {
        ipv6Address_ = other.ipv6Address_;
        onChanged();
      }
      if (!other.getCpuLoad().isEmpty()) {
        cpuLoad_ = other.cpuLoad_;
        onChanged();
      }
      if (!other.getServiceName().isEmpty()) {
        serviceName_ = other.serviceName_;
        onChanged();
      }
      if (!other.getLocalPort().isEmpty()) {
        localPort_ = other.localPort_;
        onChanged();
      }
      if (!other.getLoadblanceStategy().isEmpty()) {
        loadblanceStategy_ = other.loadblanceStategy_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.ladd.grpcx.monitor.ServiceInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.ladd.grpcx.monitor.ServiceInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object manufacturer_ = "";
    /**
     * <code>string manufacturer = 1;</code>
     */
    public java.lang.String getManufacturer() {
      java.lang.Object ref = manufacturer_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        manufacturer_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string manufacturer = 1;</code>
     */
    public com.google.protobuf.ByteString
        getManufacturerBytes() {
      java.lang.Object ref = manufacturer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        manufacturer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string manufacturer = 1;</code>
     */
    public Builder setManufacturer(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      manufacturer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string manufacturer = 1;</code>
     */
    public Builder clearManufacturer() {
      
      manufacturer_ = getDefaultInstance().getManufacturer();
      onChanged();
      return this;
    }
    /**
     * <code>string manufacturer = 1;</code>
     */
    public Builder setManufacturerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      manufacturer_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object osName_ = "";
    /**
     * <code>string osName = 2;</code>
     */
    public java.lang.String getOsName() {
      java.lang.Object ref = osName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        osName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string osName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOsNameBytes() {
      java.lang.Object ref = osName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        osName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string osName = 2;</code>
     */
    public Builder setOsName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      osName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string osName = 2;</code>
     */
    public Builder clearOsName() {
      
      osName_ = getDefaultInstance().getOsName();
      onChanged();
      return this;
    }
    /**
     * <code>string osName = 2;</code>
     */
    public Builder setOsNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      osName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object osVersion_ = "";
    /**
     * <code>string osVersion = 3;</code>
     */
    public java.lang.String getOsVersion() {
      java.lang.Object ref = osVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        osVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string osVersion = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOsVersionBytes() {
      java.lang.Object ref = osVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        osVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string osVersion = 3;</code>
     */
    public Builder setOsVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      osVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string osVersion = 3;</code>
     */
    public Builder clearOsVersion() {
      
      osVersion_ = getDefaultInstance().getOsVersion();
      onChanged();
      return this;
    }
    /**
     * <code>string osVersion = 3;</code>
     */
    public Builder setOsVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      osVersion_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object availableRam_ = "";
    /**
     * <code>string availableRam = 4;</code>
     */
    public java.lang.String getAvailableRam() {
      java.lang.Object ref = availableRam_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        availableRam_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string availableRam = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAvailableRamBytes() {
      java.lang.Object ref = availableRam_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        availableRam_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string availableRam = 4;</code>
     */
    public Builder setAvailableRam(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      availableRam_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string availableRam = 4;</code>
     */
    public Builder clearAvailableRam() {
      
      availableRam_ = getDefaultInstance().getAvailableRam();
      onChanged();
      return this;
    }
    /**
     * <code>string availableRam = 4;</code>
     */
    public Builder setAvailableRamBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      availableRam_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object totalRam_ = "";
    /**
     * <code>string totalRam = 5;</code>
     */
    public java.lang.String getTotalRam() {
      java.lang.Object ref = totalRam_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        totalRam_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string totalRam = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTotalRamBytes() {
      java.lang.Object ref = totalRam_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        totalRam_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string totalRam = 5;</code>
     */
    public Builder setTotalRam(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      totalRam_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string totalRam = 5;</code>
     */
    public Builder clearTotalRam() {
      
      totalRam_ = getDefaultInstance().getTotalRam();
      onChanged();
      return this;
    }
    /**
     * <code>string totalRam = 5;</code>
     */
    public Builder setTotalRamBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      totalRam_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object availableDisk_ = "";
    /**
     * <code>string availableDisk = 6;</code>
     */
    public java.lang.String getAvailableDisk() {
      java.lang.Object ref = availableDisk_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        availableDisk_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string availableDisk = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAvailableDiskBytes() {
      java.lang.Object ref = availableDisk_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        availableDisk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string availableDisk = 6;</code>
     */
    public Builder setAvailableDisk(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      availableDisk_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string availableDisk = 6;</code>
     */
    public Builder clearAvailableDisk() {
      
      availableDisk_ = getDefaultInstance().getAvailableDisk();
      onChanged();
      return this;
    }
    /**
     * <code>string availableDisk = 6;</code>
     */
    public Builder setAvailableDiskBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      availableDisk_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object totalDisk_ = "";
    /**
     * <code>string totalDisk = 7;</code>
     */
    public java.lang.String getTotalDisk() {
      java.lang.Object ref = totalDisk_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        totalDisk_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string totalDisk = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTotalDiskBytes() {
      java.lang.Object ref = totalDisk_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        totalDisk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string totalDisk = 7;</code>
     */
    public Builder setTotalDisk(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      totalDisk_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string totalDisk = 7;</code>
     */
    public Builder clearTotalDisk() {
      
      totalDisk_ = getDefaultInstance().getTotalDisk();
      onChanged();
      return this;
    }
    /**
     * <code>string totalDisk = 7;</code>
     */
    public Builder setTotalDiskBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      totalDisk_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object availableJVMMem_ = "";
    /**
     * <code>string availableJVMMem = 8;</code>
     */
    public java.lang.String getAvailableJVMMem() {
      java.lang.Object ref = availableJVMMem_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        availableJVMMem_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string availableJVMMem = 8;</code>
     */
    public com.google.protobuf.ByteString
        getAvailableJVMMemBytes() {
      java.lang.Object ref = availableJVMMem_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        availableJVMMem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string availableJVMMem = 8;</code>
     */
    public Builder setAvailableJVMMem(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      availableJVMMem_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string availableJVMMem = 8;</code>
     */
    public Builder clearAvailableJVMMem() {
      
      availableJVMMem_ = getDefaultInstance().getAvailableJVMMem();
      onChanged();
      return this;
    }
    /**
     * <code>string availableJVMMem = 8;</code>
     */
    public Builder setAvailableJVMMemBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      availableJVMMem_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object totalJVMMem_ = "";
    /**
     * <code>string totalJVMMem = 9;</code>
     */
    public java.lang.String getTotalJVMMem() {
      java.lang.Object ref = totalJVMMem_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        totalJVMMem_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string totalJVMMem = 9;</code>
     */
    public com.google.protobuf.ByteString
        getTotalJVMMemBytes() {
      java.lang.Object ref = totalJVMMem_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        totalJVMMem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string totalJVMMem = 9;</code>
     */
    public Builder setTotalJVMMem(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      totalJVMMem_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string totalJVMMem = 9;</code>
     */
    public Builder clearTotalJVMMem() {
      
      totalJVMMem_ = getDefaultInstance().getTotalJVMMem();
      onChanged();
      return this;
    }
    /**
     * <code>string totalJVMMem = 9;</code>
     */
    public Builder setTotalJVMMemBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      totalJVMMem_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object hostName_ = "";
    /**
     * <code>string hostName = 10;</code>
     */
    public java.lang.String getHostName() {
      java.lang.Object ref = hostName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hostName = 10;</code>
     */
    public com.google.protobuf.ByteString
        getHostNameBytes() {
      java.lang.Object ref = hostName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hostName = 10;</code>
     */
    public Builder setHostName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hostName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string hostName = 10;</code>
     */
    public Builder clearHostName() {
      
      hostName_ = getDefaultInstance().getHostName();
      onChanged();
      return this;
    }
    /**
     * <code>string hostName = 10;</code>
     */
    public Builder setHostNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hostName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ipv4Address_ = "";
    /**
     * <code>string ipv4Address = 11;</code>
     */
    public java.lang.String getIpv4Address() {
      java.lang.Object ref = ipv4Address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ipv4Address_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ipv4Address = 11;</code>
     */
    public com.google.protobuf.ByteString
        getIpv4AddressBytes() {
      java.lang.Object ref = ipv4Address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipv4Address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ipv4Address = 11;</code>
     */
    public Builder setIpv4Address(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ipv4Address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ipv4Address = 11;</code>
     */
    public Builder clearIpv4Address() {
      
      ipv4Address_ = getDefaultInstance().getIpv4Address();
      onChanged();
      return this;
    }
    /**
     * <code>string ipv4Address = 11;</code>
     */
    public Builder setIpv4AddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ipv4Address_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ipv6Address_ = "";
    /**
     * <code>string ipv6Address = 12;</code>
     */
    public java.lang.String getIpv6Address() {
      java.lang.Object ref = ipv6Address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ipv6Address_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ipv6Address = 12;</code>
     */
    public com.google.protobuf.ByteString
        getIpv6AddressBytes() {
      java.lang.Object ref = ipv6Address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipv6Address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ipv6Address = 12;</code>
     */
    public Builder setIpv6Address(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ipv6Address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ipv6Address = 12;</code>
     */
    public Builder clearIpv6Address() {
      
      ipv6Address_ = getDefaultInstance().getIpv6Address();
      onChanged();
      return this;
    }
    /**
     * <code>string ipv6Address = 12;</code>
     */
    public Builder setIpv6AddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ipv6Address_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cpuLoad_ = "";
    /**
     * <code>string cpuLoad = 13;</code>
     */
    public java.lang.String getCpuLoad() {
      java.lang.Object ref = cpuLoad_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cpuLoad_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cpuLoad = 13;</code>
     */
    public com.google.protobuf.ByteString
        getCpuLoadBytes() {
      java.lang.Object ref = cpuLoad_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cpuLoad_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cpuLoad = 13;</code>
     */
    public Builder setCpuLoad(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cpuLoad_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cpuLoad = 13;</code>
     */
    public Builder clearCpuLoad() {
      
      cpuLoad_ = getDefaultInstance().getCpuLoad();
      onChanged();
      return this;
    }
    /**
     * <code>string cpuLoad = 13;</code>
     */
    public Builder setCpuLoadBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cpuLoad_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object serviceName_ = "";
    /**
     * <code>string serviceName = 14;</code>
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string serviceName = 14;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string serviceName = 14;</code>
     */
    public Builder setServiceName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serviceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string serviceName = 14;</code>
     */
    public Builder clearServiceName() {
      
      serviceName_ = getDefaultInstance().getServiceName();
      onChanged();
      return this;
    }
    /**
     * <code>string serviceName = 14;</code>
     */
    public Builder setServiceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serviceName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object localPort_ = "";
    /**
     * <code>string localPort = 15;</code>
     */
    public java.lang.String getLocalPort() {
      java.lang.Object ref = localPort_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        localPort_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string localPort = 15;</code>
     */
    public com.google.protobuf.ByteString
        getLocalPortBytes() {
      java.lang.Object ref = localPort_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localPort_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string localPort = 15;</code>
     */
    public Builder setLocalPort(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      localPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string localPort = 15;</code>
     */
    public Builder clearLocalPort() {
      
      localPort_ = getDefaultInstance().getLocalPort();
      onChanged();
      return this;
    }
    /**
     * <code>string localPort = 15;</code>
     */
    public Builder setLocalPortBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      localPort_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object loadblanceStategy_ = "";
    /**
     * <code>string loadblanceStategy = 16;</code>
     */
    public java.lang.String getLoadblanceStategy() {
      java.lang.Object ref = loadblanceStategy_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        loadblanceStategy_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string loadblanceStategy = 16;</code>
     */
    public com.google.protobuf.ByteString
        getLoadblanceStategyBytes() {
      java.lang.Object ref = loadblanceStategy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loadblanceStategy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string loadblanceStategy = 16;</code>
     */
    public Builder setLoadblanceStategy(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      loadblanceStategy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string loadblanceStategy = 16;</code>
     */
    public Builder clearLoadblanceStategy() {
      
      loadblanceStategy_ = getDefaultInstance().getLoadblanceStategy();
      onChanged();
      return this;
    }
    /**
     * <code>string loadblanceStategy = 16;</code>
     */
    public Builder setLoadblanceStategyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      loadblanceStategy_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cn.ladd.grpcx.monitor.ServiceInfo)
  }

  // @@protoc_insertion_point(class_scope:cn.ladd.grpcx.monitor.ServiceInfo)
  private static final cn.ladd.grpcx.monitor.ServiceInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.ladd.grpcx.monitor.ServiceInfo();
  }

  public static cn.ladd.grpcx.monitor.ServiceInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServiceInfo>
      PARSER = new com.google.protobuf.AbstractParser<ServiceInfo>() {
    public ServiceInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServiceInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ServiceInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServiceInfo> getParserForType() {
    return PARSER;
  }

  public cn.ladd.grpcx.monitor.ServiceInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

