// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register.proto

package cn.ladd.grpcx.register.common;

public interface GetAllServiceNamesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.ladd.grpcx.register.common.GetAllServiceNamesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string serviceNames = 1;</code>
   */
  java.util.List<java.lang.String>
      getServiceNamesList();
  /**
   * <code>repeated string serviceNames = 1;</code>
   */
  int getServiceNamesCount();
  /**
   * <code>repeated string serviceNames = 1;</code>
   */
  java.lang.String getServiceNames(int index);
  /**
   * <code>repeated string serviceNames = 1;</code>
   */
  com.google.protobuf.ByteString
      getServiceNamesBytes(int index);
}
