// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register.proto

package cn.ladd.grpcx.register.common;

public interface GetDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.ladd.grpcx.register.common.GetDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nodeData = 1;</code>
   */
  java.lang.String getNodeData();
  /**
   * <code>string nodeData = 1;</code>
   */
  com.google.protobuf.ByteString
      getNodeDataBytes();
}
